# Generated by Django 5.2 on 2025-07-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='test',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order of the test'),
        ),
    ]
